### ISSUE TITLE
refactor bootstrapping for instance creation and initialization 

### ISSUE THREAD

**Issue by bharathkkb** [ZBejavu/gcloud-deploy-tutorial#1]
Thanks for this tutorial! I noticed that the workflow needs to be [modified](https://github.com/ZBejavu/gcloud-deploy-tutorial#after-instance-creation--firewall-rule-creation--) to comment out instance creation and initialization after initial deployment. Would it make sense to abstract these init steps to a bootstrap script that is run out of band from the CD workflow or store some kind of [metadata](https://cloud.google.com/compute/docs/storing-retrieving-metadata#querying_custom_metadata) to identify that this has been complete from within the workflow?

**Comment by ZBejavu** [comment]
Hey Bharath. Of course this makes a lot of sense. I'll look into it. Thank you !

**Comment by ZBejavu** [comment]
#2
